name: "Build Apps (Development)"
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "refactor/*"
      - "fix/*"
    tags:
      - "!#*"

jobs:
  build_apps:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    # Executable App
    # KeySwitchManager.CLI
    - run: dotnet msbuild /nologo /t:Archive /p:Configuration=Debug /p:PublishDir=$(pwd)/publish  KeySwitchManager/Sources/Applications/KeySwitchManager.CLI/publish.msbuild
    - uses: actions/upload-artifact@v2
      with:
        name: KeySwitchManager.CLI
        path: ./publish/KeySwitchManager.CLI*/
