name: Build Release
on:
  push:
    tags:
      - ver-*.*.*
      - ver-[0-9]+

jobs:
  build_apps:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - run: echo "VER_TAG=${GITHUB_REF#refs/tags/ver-}" >> $GITHUB_ENV
    # Executable App
    # KeySwitchManager.CLI
    - run: dotnet msbuild /nologo /t:Archive /p:Configuration=Release /p:PublishDir=$(pwd)/publish KeySwitchManager.CLI/publish.msbuild
    - uses: actions/upload-artifact@v2
      with:
        name: KeySwitchManager.CLI-${{ env.VER_TAG }}
        path: ./publish/KeySwitchManager.CLI*/
