name: "Build Apps (Development)"
on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "refactor/*"
    tags:
      - "!#*"

jobs:

  app-build:

    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'

    - name: CLI Build
      run: dotnet msbuild /nologo /t:Archive /p:Configuration=Debug /p:PublishDir=${{ github.workspace }}/publish %ProjectFile%
      shell: cmd
      env:
        ProjectFile: KeySwitchManager.CLI/publish.msbuild

    - name: WPF Build
      run: dotnet msbuild /nologo /t:Archive /p:Configuration=Debug /p:PublishDir=${{ github.workspace }}/publish %ProjectFile%
      shell: cmd
      env:
        ProjectFile: KeySwitchManager.Gui/KeySwitchManager.WPF/publish.msbuild

    - name: Artifact CLI
      uses: actions/upload-artifact@v2
      with:
        name: KeySwitchManager.CLI-dev
        path: ${{ github.workspace }}/publish/KeySwitchManager.CLI*/

    - name: Artifact WPF
      uses: actions/upload-artifact@v2
      with:
        name: KeySwitchManager.WPF-dev
        path: ${{ github.workspace }}/publish/KeySwitchManager.WPF*/
